### ISSUE TITLE
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

### ISSUE THREAD

**Issue by buger404** [sudo-000/Ex-Phiedit#1]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by happymimimix** [comment]
很明显，这是GPT生成的。
语言表达极其不自然！
因此，此issue不会被处理。

**Comment by happymimimix** [comment]
有任何想法意见请认真与我交谈，不要使用Chat GPT乱糊！

**Comment by KagariET01** [comment]
![image](https://github.com/sudo-000/Ex-Phiedit/assets/66681962/0378ca68-e185-4aed-a13c-9acae291f35a)  
WOW! It's GPT write! (0% sure)

**Comment by happymimimix** [comment]
> ![image](https://user-images.githubusercontent.com/66681962/252140218-0378ca68-e185-4aed-a13c-9acae291f35a.png) WOW! It's GPT write! (0% sure)

你难道不知道这个工具只能检测英文吗？
中文写的当然会被认为是0%！

你要不信，我来一句一句慢慢给你分析：
从标题后的第一句开始

>未曾听闻“删除某个功能”以此提高性能的优化方式，建议您出刊发表如下题的论文：
>《基于删除项目功能提高整体性能的程序设计优化方案》

“未曾听闻“这个表达用在这里过于正式，一个正常人提交issue时是不会使用的！
常规的说法应当是”我从未听说过“。
还有，Rectify 11通过禁用windows update和去除登录microsoft账户的功能提升系统运行效率你怎么解释？


>这里顺便为您准备了参考文献：
>XPE广告片60帧完美无卡版！. Bilibili, happy_mimimix, 2023年6月25日, https://www.bilibili.com/video/BV1MX4y1p7oF.

拿我自己亲手做的广告片过来做参考文献？我需要参考吗？
还说不是ChatGPT？
你用的是GPT 3.5吧，GPT 4都不会干出这样的蠢事，更别提真人了！


>RPE是闭源软件，您的“优化”行为无论如何也是“破解”行为。
>
>根据《中华人民共和国刑法》第二百八十六条规定：
>
>以非法侵入方式获取计算机信息系统的数据、程序、存储介质中存储的数据或者其他专有权利人的技术秘密，将其复制、传输、删除或者进行其他非法活动的，处5年以下有期徒刑或拘役，并处或单处罚金；情节严重的，处5年以上10年以下有期徒刑，并处罚金。
>
>如您从中获得利润，或造成较大影响力，以下罪名可能同样适用：
>
>根据《中华人民共和国刑法》第二百一十七条规定：
>
>侵犯著作权罪，是指以营利为目的，未经著作权人许可复制发行其文字、音像、计算机软件等作品，出版他人享有独占出版权的图书，未经制作者许可复制发行其制作的音像制品，制作、展览假冒他人署名的美术作品，违法所得数额较大或者有其他严重情节的行为。
>
>自然人犯本罪的，处三年以下有期徒刑或者拘役，并处或者单处罚金；违法所得数额巨大或者有其他特别严重情节的，处三年以上七年以下有期徒刑，并处罚金。情节特别严重，是指违法所得数额巨大或者具有其他特别严重的情节。所谓违法所得数额巨大，根据有关司法解释的规定，是指个人违法所得数额即获利数额在10万元以上，或单位违法所得数额在50万元以上。所谓其他特别严重情节，是指具有下列情形之一者：
>（1）因侵犯著作权被追究刑事责任，又犯侵犯著作权罪的；
>（2）个人非法经营数额在100万元以上，单位非法经营数额在500万元以上的；
>（3）造成其他特别严重后果或者具有其他特别严重情节的。

你觉得一个正常人提交issue有多大可能会在他说的第一句话里直接引用《中华人民共和国刑法》？
如果不是对方死不承认自己侵犯了版权，谁会没事干去翻那么长的刑法甚至还具体到第几条？
还有，你是不是忘记跟ChatGPT交代XPE是免费的了？
说我从XPE中获取了多少利润纯属无稽之谈！


>您主张更好的界面，实际上存在以下问题：
>
>颜色搭配存在严重问题
>设计风格过于古早，其中一部分的设计风格仍停留在2000年初
>多种设计风格混杂，难以形成美感


2000年初的设计风格正是我最渴望的！拟物化YYDS！
专门做旧的东西竟被嘲笑过于古早！笑死了。
还有，“颜色搭配存在严重问题“表达依然过于正式。常规说法应当是：“颜色搭配不恰当”


>您主张“显示列表所有内容”，移动了列表框的位置，实际上这有以下不妥之处：
>
>擅自更改用户使用习惯
>不符合人机交互设计原则
>您主张您的改版可以支持更大量的音符播放，实际上，
>物量达到您所追求运行流畅的目标优化物量数，这张谱面很可能是千年难见的世纪大粪谱。


我哪里有提到过“显示列表所有内容”？
ChatGPT答非所问了属于是。
而且这句话中大量使用了“您”，你觉得这是issue里该出现的字样吗？
日常交流谁会天天把“您”挂在嘴边？
表达过于正式！

整个issue几乎看不到一个“我”的字样，这是人能写出来的东西吗？
正因为ChatGPT不是真人，于是便会在回答中尽可能避免讨论它自己。
如果这个issue真的是自己亲手写的被误认为是ChatGPT，正常人是不会尝试用检测器去证明这不是ChatGPT的！
如果你只是想整活，请你到其他repo里去搞。我这不欢迎你！
若这真的是你自己亲手写的，那我必须告诉你：
像写学术论文一样提交issue不会引起开发者的注意！
你这样只会被更多的开发者误认为是ChatGPT代写的然后选择不理你！


你很幸运遇上了我，其他人是不可能跟你这么细致地分析的！
一句话不说直接按一下Close完事。
我只是不忍心看你以后再继续栽进更大的坑，跟你多说了亿句。
有任何其他想法欢迎一起交流讨论。

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by KagariET01** [comment]
> 我哪里有提到过“显示列表所有内容”？  

~~Wow, you never mention it!~~
![image](https://github.com/sudo-000/Ex-Phiedit/assets/66681962/21d0801e-8e31-4c9d-9efd-719756e2ea3a)

**Comment by KagariET01** [comment]
假設一首歌5 min，1秒10個notes  
5*60*10=3,000 (notes)  
再假設這是8K譜面，同樣1秒10個notes  
3000*8=24,000 (notes)  
遠低於你所說的100K notes  
目前Phigros官譜紀錄也只有4000notes，且這譜面也是愚人節譜面  
你說RPE最高只能放20K notes，也已經很夠用了  
### ***沒必要上到100K notes***  
再者，你也承認你使用逆向工程軟體  
未經作者同意擅自修改軟體並公開會觸犯到智慧財產權法等相關法條  
請不要再掩蓋自己的罪刑了  
(中國法律我不是很了解，若有錯誤，可幫忙補充，謝謝)  
![image](https://github.com/sudo-000/Ex-Phiedit/assets/66681962/df651cd5-6e56-4024-9953-f7f8b39f9906)

**Comment by happymimimix** [comment]
> 🤔呃，你也不看看自己Github几个contribution，没多少项目经验就不要张口就来了。 简要直白的说辞、清晰的排版自然更能让人接受 像你这个回复，废话连篇，重点不突出，是我看到就会直接block的类型😰


更明确的解释说明居然被你称之为废话实在可笑！
还有，你怎么不去数数rpe有几个 contribute？
不也就cmdysj一个？

**Comment by happymimimix** [comment]
> 假設一首歌5 min，1秒10個notes 5_60_10=3,000 (notes) 再假設這是8K譜面，同樣1秒10個notes 3000*8=24,000 (notes) 遠低於你所說的100K notes 目前Phigros官譜紀錄也只有4000notes，且這譜面也是愚人節譜面 你說RPE最高只能放20K notes，也已經很夠用了
> 
> ### _**沒必要上到100K notes**_
> 再者，你也承認你使用逆向工程軟體修改RPE了 未經作者同意擅自修改軟體並公開會觸犯到智慧財產權法等相關法條 請不要再掩蓋自己的罪刑了 (中國法律我不是很了解，若有錯誤，可幫忙補充，謝謝) ![image](https://user-images.githubusercontent.com/66681962/255167978-df651cd5-6e56-4024-9953-f7f8b39f9906.png)

你这样的行为与“等我有钱了，我要买两倍豆浆，喝一杯倒一杯。”没有区别！
这不是你能不能买得起两倍豆浆的问题，这是对你自己劳动成果的不尊重，是对资源的浪费，是你道德修养败坏的体现。
难道你们家吃饭都没有说过要吃多少盛多少吗？
盛满满一大碗剩下半碗不吃，然后说我们家又不是买不起这么多米你看看你爸妈是什么反应。
不得把你打死？

你要知道cpu每执行一条指令都是要消耗很多能量的。
具体数值各个cpu不同，要自己测量了才知道。
使用xpe写谱，同样的操作可以比rpe少执行上千条指令。
就以复制粘贴为例，xpe每复制一次就要比rpe少执行约2000条指令。
假设某个cpu执行一条指令需要消耗10焦耳能量，复制10个note就能节省100焦耳。
假设我今天总共使用复制粘贴20次，那么总计节省2000焦耳。
以上所有这些再乘以用户数量，这里假设50人，每人平均每天使用20次复制粘贴。就可以节省10万焦耳！
一个较大的谱面多半都要写好几天才能完工，这里假设20天，那么50人用xpe每人写一张谱总计节省200万焦耳！
且这还仅仅是复制粘贴，再把放置音符，事件，移动，翻转，预览，等等一系列常用操作算上更是不得了！！！
可不要小看了这2000条cpu指令，积少成多，最后它就能变成一个很大的数字！

对于软件的性能优化，我看到的不是我用450个patch使复制粘贴音符的操作快了多少倍，而是我用450个Patch使一次复制粘贴的操作少消耗了多少能量，发电厂可以少排放多少吨煤灰，少排放多少吨二氧化碳。以此，我可以把世界末日再推迟多少天。
我看到的是我用这450个patch拯救了整个世界！

短期看来可能没什么太大的影响，但如果持续几十年几百年，照刚刚的逻辑你自己算算看？
别跟我扯别的，你自己去算，严禁逃避。
在你给我这个结果之前我不回答你的任何问题。

**Comment by happymimimix** [comment]
> > 我哪里有提到过“显示列表所有内容”？
> 
> ~Wow, you never mention it!~ ![image](https://user-images.githubusercontent.com/66681962/254771580-21d0801e-8e31-4c9d-9efd-719756e2ea3a.png)

抱歉，我没有意识到你说的列表原来是指的这个。

**Comment by happymimimix** [comment]
> 你知道RPE为什么不让改id吗？ 没有多少项目经验应该是不会懂吧，可能连GUID是什么都不知道。

你有自己把rpe的源代码反编译出来分析吗？
谱面id与guid完全没关系的好吧。
它就是个字符串，甚至都不是integer。

**Comment by happymimimix** [comment]
> 我就这么说吧，你用删除功能的方式得到了性能提升，你这个不叫对功能的优化，这是直接摆烂了 你仿佛在说：“应对困难最好的方法就是让困难不存在”

让困难不存在难道不也是解决掉它的方法之一吗？
我不管用什么方法，怎么实现的，反正最后结果做到了就OK！
不管黑猫白猫能捉住老鼠的就是好猫。

**Comment by happymimimix** [comment]
> 你不如多去看看别人怎么提issue的，只靠自己想象猜测张口就来我是挺无语的。 计算机方面的奖项实话说我是拿到手软的，我还是起码有一点资格好好和你说说 你逆向了就是逆向了，逆向本身就是不尊重原作者的可以理解吗？不要再美化自己的恶行，给自己的行为找借口了。 不违法不等于它就是正确的，可以理解吗？ 你但凡措辞不要这么夸张自大，不要体现你的专业知识多么匮乏，你但凡尊重一点原作者，事情都小一些，能理解吗，小朋友。

什么想象猜测，我有详细的分析过程。
怎么？还嫌不够详细？
计算机拿奖跟xpe有何关系？这就是你抬杠的借口吗？

**Comment by happymimimix** [comment]
> 你不如多去看看别人怎么提issue的，只靠自己想象猜测张口就来我是挺无语的。 计算机方面的奖项实话说我是拿到手软的，我还是起码有一点资格好好和你说说 你逆向了就是逆向了，逆向本身就是不尊重原作者的可以理解吗？不要再美化自己的恶行，给自己的行为找借口了。 不违法不等于它就是正确的，可以理解吗？ 你但凡措辞不要这么夸张自大，不要体现你的专业知识多么匮乏，你但凡尊重一点原作者，事情都小一些，能理解吗，小朋友。

我跟作者提出过优化一下性能，根本不理我。
没办法只能自己改了。
如果不信你自己发消息给cmdysj去问，你看他是怎么回复你的。

**Comment by happymimimix** [comment]
我提醒一下我是有权利直接hide你的comment的。
再继续抬杠你试试？

**Comment by happymimimix** [comment]
我从不随意删评论，除非遇到解释地很明确却依然假装不懂绕开话题继续抬杠专门来整我的人。

**Comment by buger404** [comment]
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X
R0VUIE9VVCBPRiBHSVRIVUIgTk9X

**Comment by buger404** [comment]
不多说了，我会就具体违规情况与Github团队取得联系
