### ISSUE TITLE
使用“!) FPSConfig.exe”时报错

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [sudo-000/Ex-Phiedit#2]
![image](https://github.com/sudo-000/Ex-Phiedit/assets/117198625/fb895e14-a87d-499b-84f6-16390405800a)
![image](https://github.com/sudo-000/Ex-Phiedit/assets/117198625/ad549f04-48b3-4abc-8f8e-f1f63c1a1c9e)

**Comment by happymimimix** [comment]
请以管理员身份运行

**Comment by S-t-e-v-e-e** [comment]
> 请以管理员身份运行

已经使用管理员身份运行了（图1）

**Comment by happymimimix** [comment]
> > 请以管理员身份运行
> 
> 已经使用管理员身份运行了（图1）

你必须先打开XPE，然后再进行配置。
配置好后千万不要关闭XPE，因为patch是写在内存里的，关掉了就没了。
下次打开XPE时需要重新配置一遍。
若想要修改默认设置，请观看114514NotAvailable的仓库里的readme中的视频。
